# Generated by Django 2.1.7 on 2019-03-31 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('desc', models.TextField(max_length=900, verbose_name='نبذة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('img', models.ImageField(upload_to='photos/%Y/%m', verbose_name='صورة')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='تاريخ الاضافة')),
            ],
            options={
                'verbose_name': 'صفحة',
                'verbose_name_plural': 'صفحات',
            },
        ),
    ]
