# Generated by Django 2.1.7 on 2019-04-01 07:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='desc',
            field=models.TextField(max_length=300, verbose_name='نبذة'),
        ),
    ]
