# Generated by Django 2.1.7 on 2019-03-29 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'التصنيف',
                'verbose_name_plural': 'التصانيف',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('desc', models.TextField(blank=True, max_length=800)),
                ('content', models.TextField(default='')),
                ('img', models.ImageField(upload_to='photos/%Y/%m')),
                ('is_publish', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.Category')),
            ],
        ),
    ]
