# Generated by Django 2.1.7 on 2019-03-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'مشروع', 'verbose_name_plural': 'مشاريع'},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ManyToManyField(to='project.Category'),
        ),
    ]
