# Generated by Django 2.1.7 on 2019-03-31 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190330_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='اسم التصنيف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='عنوان الرابط'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.ManyToManyField(to='project.Category', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='content',
            field=models.TextField(default='', verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='تاريخ الاضافة'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=models.TextField(blank=True, max_length=800, verbose_name='نبذة'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.ImageField(upload_to='photos/%Y/%m', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='نشر'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=250, verbose_name='العنوان'),
        ),
    ]
