# Generated by Django 2.1.7 on 2019-03-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190331_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='img',
            new_name='image',
        ),
    ]
