# Generated by Django 2.1.7 on 2019-03-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qalo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('content', models.TextField(default='', verbose_name='ايش قالو يالحبيب')),
                ('is_publish', models.BooleanField(default=True, verbose_name='ننشر ؟')),
                ('image', models.ImageField(upload_to='photos/qalo/%Y/%m', verbose_name='ارفع صورة اللي قال او اللوقو')),
            ],
            options={
                'verbose_name': 'قالو عنّا',
                'verbose_name_plural': 'قالو عنّا',
            },
        ),
    ]
