# Generated by Django 2.1.7 on 2019-03-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qalo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qalo',
            name='desc',
            field=models.CharField(default='', max_length=250, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='qalo',
            name='title',
            field=models.CharField(max_length=250, verbose_name='الاسم'),
        ),
    ]
